### ISSUE TITLE
Text content overlaps with sketchy border

### ISSUE THREAD

**Issue by itaditya** [wiredjs/wired-textarea#4]
Take a look at this, the `e` is overlapping with the border.

![wiredjs com_showcase html](https://user-images.githubusercontent.com/15871340/40573752-86f2dffa-60e3-11e8-8b06-0ab20b36c7e1.png)

**Comment by pshihn** [comment]
I thinks some overlap is expected out of randomness. It may not happen in the next render. 
I think the better solution here would be to provide a custom css property for the user of the control to add the padding they want.

**Comment by itaditya** [comment]
@pshihn I tested the textarea multiple times, the overlap happens everytime

**Comment by pshihn** [comment]
You're probably right. I have left this issue open for that reason. 
Just saying that while resolving this, we should make the padding property configurable.

**Comment by itaditya** [comment]
Ok, I'd love to get this done. I have played with css custom properties before but I have no experience with polymer or web components. Please can you guide me on how to accomplish the task

**Comment by pshihn** [comment]
I noticed that there was an issue with mismatched sizing of textarea and its mirror (used for auto grow). I have fixed that (in v0.5.3) which might solve most of the overlap issues. 

There's still an issue about adding custom padding. So i've created a separate issue for that: https://github.com/wiredjs/wired-textarea/issues/6 You can take that on if you like. I'm going to add some notes for you there.
