### ISSUE TITLE
Ability to add custom padding 

### ISSUE THREAD

**Issue by pshihn** [wiredjs/wired-textarea#6]
Probably add a custom property like the one used in the [wired-slider](https://github.com/wiredjs/wired-slider/blob/master/wired-slider.js) Notice: `--wired-slider-knob-color`

New property called `--wired-textarea-padding` should be used with a default value of 0px. 

The property should be applied to the textarea AND the mirror div.

**Comment by itaditya** [comment]
Shouldn't the default value be 5px as seen here https://github.com/wiredjs/wired-textarea/blob/master/wired-textarea.js#L103

**Comment by pshihn** [comment]
@itaditya Yes you're right. My bad. 5px

**Comment by itaditya** [comment]
@pshihn I have updated the PR #7 , please review it
